export const ErrorCode = {
  PLATFORM_KEY_MISSING: 'PLATFORM_KEY_MISSING',
  PLATFORM_KEY_INVALID: 'PLATFORM_KEY_INVALID',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_ALREADY_SUSPENDED: 'TENANT_ALREADY_SUSPENDED',
  TENANT_NOT_SUSPENDED: 'TENANT_NOT_SUSPENDED',
  BRANCH_NAME_TAKEN: 'BRANCH_NAME_TAKEN',
  TENANT_NAME_TAKEN: 'TENANT_NAME_TAKEN',
  INVALID_UUID: 'INVALID_UUID',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
